// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createCalendar = `-- name: CreateCalendar :exec
CALL create_calendar(
	?,
	?,
	?,
	?,
	?,
	?,
	@out_calendar_id
)
`

type CreateCalendarParams struct {
	ActorUserID  interface{}
	Name         interface{}
	Color        interface{}
	Ical         interface{}
	Description  interface{}
	AesSecretKey interface{}
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) error {
	_, err := q.db.ExecContext(ctx, createCalendar,
		arg.ActorUserID,
		arg.Name,
		arg.Color,
		arg.Ical,
		arg.Description,
		arg.AesSecretKey,
	)
	return err
}

const deleteCalendar = `-- name: DeleteCalendar :execrows
DELETE FROM calendars
WHERE calendar_id = ?
	AND owner_user_id = ?
`

type DeleteCalendarParams struct {
	CalendarID  int64
	ActorUserID int64
}

func (q *Queries) DeleteCalendar(ctx context.Context, arg DeleteCalendarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCalendar, arg.CalendarID, arg.ActorUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCalendar = `-- name: GetCalendar :one
SELECT
	owner_user_id,
	name,
	color,
	description,
	AES_DECRYPT(cwh.ical_encrypted, ?) AS ical,
	cwh.created_at AS updated_at
FROM calendars AS c
INNER JOIN calendar_writes_history AS cwh
	ON c.calendar_id = cwh.calendar_id
WHERE c.calendar_id = ?
	AND cwh.created_at = (
		SELECT MAX(created_at)
		FROM calendar_writes_history AS cwh2
		WHERE cwh2.calendar_id = cwh.calendar_id
	)
	AND (
		c.owner_user_id = ?
		OR EXISTS (
			SELECT 1
			FROM organization_calendars_history AS och
			INNER JOIN organization_members_history AS omh
				ON och.organization_id = omh.organization_id
			WHERE och.calendar_id = c.calendar_id
				AND och.added = TRUE
				AND och.created_at = (
					SELECT MAX(created_at)
					FROM organization_calendars_history AS och2
					WHERE och2.calendar_id = och.calendar_id
				)
				AND omh.member_user_id = ?
				AND omh.added = TRUE
				AND omh.created_at = (
					SELECT MAX(created_at)
					FROM organization_members_history AS omh2
					WHERE omh2.organization_id = omh.organization_id
						AND omh2.member_user_id = omh.member_user_id
				)
		)
	)
`

type GetCalendarParams struct {
	AesSecretKey string
	CalendarID   int64
	ActorUserID  int64
}

type GetCalendarRow struct {
	OwnerUserID int64
	Name        string
	Color       string
	Description sql.Null[string]
	Ical        string
	UpdatedAt   time.Time
}

func (q *Queries) GetCalendar(ctx context.Context, arg GetCalendarParams) (GetCalendarRow, error) {
	row := q.db.QueryRowContext(ctx, getCalendar,
		arg.AesSecretKey,
		arg.CalendarID,
		arg.ActorUserID,
		arg.ActorUserID,
	)
	var i GetCalendarRow
	err := row.Scan(
		&i.OwnerUserID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.Ical,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCalendarMetadata = `-- name: UpdateCalendarMetadata :execrows
UPDATE calendars
SET name = COALESCE(?, name),
	color = COALESCE(?, color),
	description = COALESCE(?, description)
WHERE calendar_id = ?
	AND owner_user_id = ?
`

type UpdateCalendarMetadataParams struct {
	Name        sql.Null[string]
	Color       sql.Null[string]
	Description sql.Null[string]
	CalendarID  int64
	ActorUserID int64
}

func (q *Queries) UpdateCalendarMetadata(ctx context.Context, arg UpdateCalendarMetadataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCalendarMetadata,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.CalendarID,
		arg.ActorUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
