// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar_writes.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const getCalendarWrite = `-- name: GetCalendarWrite :one
SELECT cwh.calendar_id,
	writer_user_id,
	AES_DECRYPT(ical_encrypted, ?) AS ical,
	created_at
FROM calendar_writes_history AS cwh
INNER JOIN calendars AS c
	ON cwh.calendar_id = c.calendar_id
WHERE cwh.calendar_write_event_id = ?
	AND c.owner_user_id = ?
`

type GetCalendarWriteParams struct {
	AesSecretKey         string
	CalendarWriteEventID int64
	ActorUserID          int64
}

type GetCalendarWriteRow struct {
	CalendarID   int64
	WriterUserID sql.Null[int64]
	Ical         string
	CreatedAt    time.Time
}

func (q *Queries) GetCalendarWrite(ctx context.Context, arg GetCalendarWriteParams) (GetCalendarWriteRow, error) {
	row := q.db.QueryRowContext(ctx, getCalendarWrite, arg.AesSecretKey, arg.CalendarWriteEventID, arg.ActorUserID)
	var i GetCalendarWriteRow
	err := row.Scan(
		&i.CalendarID,
		&i.WriterUserID,
		&i.Ical,
		&i.CreatedAt,
	)
	return i, err
}

const getCalendarWrites = `-- name: GetCalendarWrites :many
SELECT calendar_write_event_id
FROM calendar_writes_history AS cwh
INNER JOIN calendars AS c
	ON cwh.calendar_id = c.calendar_id
WHERE c.calendar_id = ?
	AND c.owner_user_id = ?
`

type GetCalendarWritesParams struct {
	CalendarID  int64
	ActorUserID int64
}

func (q *Queries) GetCalendarWrites(ctx context.Context, arg GetCalendarWritesParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarWrites, arg.CalendarID, arg.ActorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var calendar_write_event_id int64
		if err := rows.Scan(&calendar_write_event_id); err != nil {
			return nil, err
		}
		items = append(items, calendar_write_event_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeCalendar = `-- name: WriteCalendar :execlastid
INSERT INTO calendar_writes_history (
	calendar_id,
	writer_user_id,
	ical_encrypted,
	created_at
) SELECT
	?,
	?,
	AES_ENCRYPT(?, ?),
	NOW(6)
WHERE EXISTS (
	SELECT 1
	FROM calendars AS c
	WHERE c.calendar_id = ?
		AND c.owner_user_id = ?
) OR EXISTS (
	SELECT 1
	FROM current_organization_calendars AS coc
	INNER JOIN current_member_roles AS cmr
		ON coc.organization_id = cmr.organization_id
			AND cmr.member_user_id = ?
			AND cmr.role IN ('owner', 'admin')
	WHERE coc.calendar_id = ?
)
`

type WriteCalendarParams struct {
	CalendarID   int64
	ActorUserId2 sql.Null[int64]
	Ical         string
	AesSecretKey string
	ActorUserID  int64
}

func (q *Queries) WriteCalendar(ctx context.Context, arg WriteCalendarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, writeCalendar,
		arg.CalendarID,
		arg.ActorUserId2,
		arg.Ical,
		arg.AesSecretKey,
		arg.CalendarID,
		arg.ActorUserID,
		arg.ActorUserID,
		arg.CalendarID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
