// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_memberships.sql

package store

import (
	"context"
)

const joinOrganization = `-- name: JoinOrganization :exec
CALL join_organization(
	?,
	?
)
`

type JoinOrganizationParams struct {
	ActorUserID    interface{}
	OrganizationID interface{}
}

func (q *Queries) JoinOrganization(ctx context.Context, arg JoinOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, joinOrganization, arg.ActorUserID, arg.OrganizationID)
	return err
}

const leaveOrganization = `-- name: LeaveOrganization :exec
CALL leave_organization(
	?,
	?
)
`

type LeaveOrganizationParams struct {
	ActorUserID    interface{}
	OrganizationID interface{}
}

func (q *Queries) LeaveOrganization(ctx context.Context, arg LeaveOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, leaveOrganization, arg.ActorUserID, arg.OrganizationID)
	return err
}
