// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createOrganization = `-- name: CreateOrganization :exec
CALL create_organization(
	?,
	?,
	?,
	?,
	@out_organization_id
)
`

type CreateOrganizationParams struct {
	ActorUserID         interface{}
	Name                interface{}
	RequiresJoinRequest interface{}
	Description         interface{}
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization,
		arg.ActorUserID,
		arg.Name,
		arg.RequiresJoinRequest,
		arg.Description,
	)
	return err
}

const deleteOrganization = `-- name: DeleteOrganization :execrows
DELETE o
FROM organizations AS o
INNER JOIN member_roles_history AS mrh
	ON o.organization_id = mrh.organization_id
WHERE o.organization_id = ?
	AND mrh.member_user_id = ?
	AND mrh.role = 'owner'
	AND mrh.created_at = (
		SELECT MAX(created_at)
		FROM member_roles_history AS mrh2
		WHERE o.organization_id = mrh2.organization_id
			AND mrh.member_user_id = mrh2.member_user_id
	)
`

type DeleteOrganizationParams struct {
	OrganizationID int64
	ActorUserID    int64
}

func (q *Queries) DeleteOrganization(ctx context.Context, arg DeleteOrganizationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrganization, arg.OrganizationID, arg.ActorUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOrganization = `-- name: GetOrganization :one
SELECT name, requires_join_request, created_at, description
FROM organizations
WHERE organization_id = ?
`

type GetOrganizationRow struct {
	Name                string
	RequiresJoinRequest bool
	CreatedAt           time.Time
	Description         sql.Null[string]
}

func (q *Queries) GetOrganization(ctx context.Context, organizationID int64) (GetOrganizationRow, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, organizationID)
	var i GetOrganizationRow
	err := row.Scan(
		&i.Name,
		&i.RequiresJoinRequest,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const getOrganizations = `-- name: GetOrganizations :many
SELECT organization_id
FROM organizations
`

func (q *Queries) GetOrganizations(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var organization_id int64
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :execrows
UPDATE organizations AS o
INNER JOIN member_roles_history AS mrh
	ON o.organization_id = mrh.organization_id
SET o.name = COALESCE(?, o.name),
	o.description = COALESCE(?, o.description),
	o.requires_join_request = COALESCE(
		?,
		o.requires_join_request
	)
WHERE o.organization_id = ?
	AND mrh.member_user_id = ?
	AND mrh.role = 'owner'
	AND mrh.created_at = (
		SELECT MAX(created_at)
		FROM member_roles_history AS mrh2
		WHERE o.organization_id = mrh2.organization_id
			AND mrh.member_user_id = mrh2.member_user_id
	)
`

type UpdateOrganizationParams struct {
	Name                sql.Null[string]
	Description         sql.Null[string]
	RequiresJoinRequest sql.Null[bool]
	OrganizationID      int64
	ActorUserID         int64
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOrganization,
		arg.Name,
		arg.Description,
		arg.RequiresJoinRequest,
		arg.OrganizationID,
		arg.ActorUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
