// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_calendars.sql

package store

import (
	"context"
)

const getOrganizationCalendars = `-- name: GetOrganizationCalendars :many
SELECT calendar_id
FROM current_organization_calendars AS coc
INNER JOIN current_memberships AS cm
	ON coc.organization_id = cm.organization_id
WHERE coc.organization_id = ?
	AND cm.member_user_id = ?
`

type GetOrganizationCalendarsParams struct {
	OrganizationID int64
	ActorUserID    int64
}

func (q *Queries) GetOrganizationCalendars(ctx context.Context, arg GetOrganizationCalendarsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizationCalendars, arg.OrganizationID, arg.ActorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var calendar_id int64
		if err := rows.Scan(&calendar_id); err != nil {
			return nil, err
		}
		items = append(items, calendar_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleShareUserCalendar = `-- name: ToggleShareUserCalendar :exec
CALL toggle_share_user_calendar(
	?,
	?,
	?
)
`

type ToggleShareUserCalendarParams struct {
	ActorUserID    interface{}
	OrganizationID interface{}
	CalendarID     interface{}
}

func (q *Queries) ToggleShareUserCalendar(ctx context.Context, arg ToggleShareUserCalendarParams) error {
	_, err := q.db.ExecContext(ctx, toggleShareUserCalendar, arg.ActorUserID, arg.OrganizationID, arg.CalendarID)
	return err
}
