// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_labels.sql

package store

import (
	"context"
	"database/sql"
)

const attachUserLabel = `-- name: AttachUserLabel :exec
INSERT INTO calendars_users_labels (calendar_id, user_label_id)
SELECT ?, ?
WHERE EXISTS (
	SELECT 1
	FROM users_labels AS ul
	WHERE ul.user_label_id = ?
	AND ul.user_id = ?
)
`

type AttachUserLabelParams struct {
	CalendarID  int64
	UserLabelID int64
	ActorUserID int64
}

func (q *Queries) AttachUserLabel(ctx context.Context, arg AttachUserLabelParams) error {
	_, err := q.db.ExecContext(ctx, attachUserLabel,
		arg.CalendarID,
		arg.UserLabelID,
		arg.UserLabelID,
		arg.ActorUserID,
	)
	return err
}

const createUserLabel = `-- name: CreateUserLabel :execlastid
INSERT INTO users_labels (user_id, name, color)
VALUES (?, ?, ?)
`

type CreateUserLabelParams struct {
	ActorUserID int64
	Name        string
	Color       string
}

func (q *Queries) CreateUserLabel(ctx context.Context, arg CreateUserLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createUserLabel, arg.ActorUserID, arg.Name, arg.Color)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteUserLabel = `-- name: DeleteUserLabel :execrows
DELETE FROM users_labels
WHERE user_label_id = ?
	AND user_id = ?
`

type DeleteUserLabelParams struct {
	UserLabelID int64
	ActorUserID int64
}

func (q *Queries) DeleteUserLabel(ctx context.Context, arg DeleteUserLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserLabel, arg.UserLabelID, arg.ActorUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const detachUserLabel = `-- name: DetachUserLabel :execrows
DELETE cul
FROM calendars_users_labels AS cul
INNER JOIN users_labels AS ul
	ON cul.user_label_id = ul.user_label_id
WHERE cul.calendar_id = ?
	AND ul.user_label_id = ?
	AND ul.user_id = ?
`

type DetachUserLabelParams struct {
	CalendarID  int64
	UserLabelID int64
	ActorUserID int64
}

func (q *Queries) DetachUserLabel(ctx context.Context, arg DetachUserLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, detachUserLabel, arg.CalendarID, arg.UserLabelID, arg.ActorUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserLabel = `-- name: GetUserLabel :one
SELECT name, color
FROM users_labels
WHERE user_label_id = ?
	AND user_id = ?
`

type GetUserLabelParams struct {
	UserLabelID int64
	ActorUserID int64
}

type GetUserLabelRow struct {
	Name  string
	Color string
}

func (q *Queries) GetUserLabel(ctx context.Context, arg GetUserLabelParams) (GetUserLabelRow, error) {
	row := q.db.QueryRowContext(ctx, getUserLabel, arg.UserLabelID, arg.ActorUserID)
	var i GetUserLabelRow
	err := row.Scan(&i.Name, &i.Color)
	return i, err
}

const updateUserLabel = `-- name: UpdateUserLabel :execrows
UPDATE users_labels
SET name = COALESCE(?, name),
	color = COALESCE(?, color)
WHERE user_label_id = ?
	AND user_id = ?
`

type UpdateUserLabelParams struct {
	Name        sql.Null[string]
	Color       sql.Null[string]
	UserLabelID int64
	ActorUserID int64
}

func (q *Queries) UpdateUserLabel(ctx context.Context, arg UpdateUserLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserLabel,
		arg.Name,
		arg.Color,
		arg.UserLabelID,
		arg.ActorUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
