// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_sessions.sql

package store

import (
	"context"
	"time"
)

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO users_sessions (id, user_id, expires_at)
VALUES (
	?,
	?,
	FROM_UNIXTIME(UNIX_TIMESTAMP() + ?)
)
`

type CreateUserSessionParams struct {
	ID         []byte
	UserID     int32
	TtlSeconds interface{}
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, createUserSession, arg.ID, arg.UserID, arg.TtlSeconds)
	return err
}

const getUserSession = `-- name: GetUserSession :one
SELECT user_id, expires_at, NOW(6) AS db_time
FROM users_sessions
WHERE id = ?
`

type GetUserSessionRow struct {
	UserID    int32
	ExpiresAt time.Time
	DBTime    time.Time
}

func (q *Queries) GetUserSession(ctx context.Context, sessionID []byte) (GetUserSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSession, sessionID)
	var i GetUserSessionRow
	err := row.Scan(&i.UserID, &i.ExpiresAt, &i.DBTime)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
DELETE FROM users_sessions
WHERE user_id = ?
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, actorUserID int32) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserSessions, actorUserID)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
DELETE FROM users_sessions
WHERE id = ?
`

func (q *Queries) RevokeUserSession(ctx context.Context, sessionID []byte) error {
	_, err := q.db.ExecContext(ctx, revokeUserSession, sessionID)
	return err
}
