// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execlastid
INSERT INTO users (
	email,
	first_name,
	last_name,
	password_hash,
	middle_name
) VALUES (
	?,
	?,
	?,
	?,
	?
)
`

type CreateUserParams struct {
	Email        string
	FirstName    string
	LastName     string
	PasswordHash []byte
	MiddleName   sql.Null[string]
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.MiddleName,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, actorUserID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, actorUserID)
	return err
}

const getLoginUser = `-- name: GetLoginUser :one
SELECT id, password_hash
FROM users
WHERE email = ?
`

type GetLoginUserRow struct {
	ID           int32
	PasswordHash []byte
}

func (q *Queries) GetLoginUser(ctx context.Context, email string) (GetLoginUserRow, error) {
	row := q.db.QueryRowContext(ctx, getLoginUser, email)
	var i GetLoginUserRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT email, first_name, last_name, middle_name
FROM users
WHERE id = ?
`

type GetUserRow struct {
	Email      string
	FirstName  string
	LastName   string
	MiddleName sql.Null[string]
}

func (q *Queries) GetUser(ctx context.Context, userID int32) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i GetUserRow
	err := row.Scan(
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
	)
	return i, err
}

const updateLoginUser = `-- name: UpdateLoginUser :exec
UPDATE users
SET email = COALESCE(?, email),
	password_hash = COALESCE(?, password_hash)
WHERE id = ?
`

type UpdateLoginUserParams struct {
	Email        sql.Null[string]
	PasswordHash sql.Null[[]byte]
	ActorUserID  int32
}

func (q *Queries) UpdateLoginUser(ctx context.Context, arg UpdateLoginUserParams) error {
	_, err := q.db.ExecContext(ctx, updateLoginUser, arg.Email, arg.PasswordHash, arg.ActorUserID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET first_name = COALESCE(?, first_name),
	last_name = COALESCE(?, last_name),
	middle_name = COALESCE(?, middle_name)
WHERE id = ?
`

type UpdateUserParams struct {
	FirstName   sql.Null[string]
	LastName    sql.Null[string]
	MiddleName  sql.Null[string]
	ActorUserID int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.ActorUserID,
	)
	return err
}
