// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profiles.sql

package store

import (
	"context"
)

const getUserCalendarLabels = `-- name: GetUserCalendarLabels :many
SELECT ul.user_label_id
FROM users_labels AS ul
INNER JOIN calendars_users_labels AS cul
    ON cul.user_label_id = ul.user_label_id
WHERE cul.calendar_id = ?
    AND ul.user_id = ?
`

type GetUserCalendarLabelsParams struct {
	CalendarID  int64
	ActorUserID int64
}

func (q *Queries) GetUserCalendarLabels(ctx context.Context, arg GetUserCalendarLabelsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getUserCalendarLabels, arg.CalendarID, arg.ActorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_label_id int64
		if err := rows.Scan(&user_label_id); err != nil {
			return nil, err
		}
		items = append(items, user_label_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLabels = `-- name: GetUserLabels :many
SELECT user_label_id
FROM users_labels
WHERE user_id = ?
`

func (q *Queries) GetUserLabels(ctx context.Context, actorUserID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getUserLabels, actorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_label_id int64
		if err := rows.Scan(&user_label_id); err != nil {
			return nil, err
		}
		items = append(items, user_label_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT organization_id
FROM organization_members_history AS omh
WHERE omh.member_user_id = ?
	AND omh.added = TRUE
	AND omh.created_at = (
		SELECT MAX(created_at)
		FROM organization_members_history AS omh2
		WHERE omh2.organization_id = omh.organization_id
			AND omh2.member_user_id = omh.member_user_id
	)
`

func (q *Queries) GetUserOrganizations(ctx context.Context, actorUserID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrganizations, actorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var organization_id int64
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOwnedCalendars = `-- name: GetUserOwnedCalendars :many
SELECT calendar_id
FROM calendars
WHERE owner_user_id = ?
`

func (q *Queries) GetUserOwnedCalendars(ctx context.Context, actorUserID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getUserOwnedCalendars, actorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var calendar_id int64
		if err := rows.Scan(&calendar_id); err != nil {
			return nil, err
		}
		items = append(items, calendar_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
