// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_sessions.sql

package store

import (
	"context"
	"time"
)

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO users_sessions (session_hash, user_id, expires_at)
VALUES (
	?,
	?,
	FROM_UNIXTIME(UNIX_TIMESTAMP() + ?)
)
`

type CreateUserSessionParams struct {
	SessionHash []byte
	UserID      int64
	TtlSeconds  interface{}
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, createUserSession, arg.SessionHash, arg.UserID, arg.TtlSeconds)
	return err
}

const getUserSession = `-- name: GetUserSession :one
SELECT user_id, expires_at, NOW(6) AS db_time
FROM users_sessions
WHERE session_hash = ?
`

type GetUserSessionRow struct {
	UserID    int64
	ExpiresAt time.Time
	DBTime    time.Time
}

func (q *Queries) GetUserSession(ctx context.Context, sessionHash []byte) (GetUserSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSession, sessionHash)
	var i GetUserSessionRow
	err := row.Scan(&i.UserID, &i.ExpiresAt, &i.DBTime)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
DELETE FROM users_sessions
WHERE user_id = ?
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, actorUserID int64) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserSessions, actorUserID)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
DELETE FROM users_sessions
WHERE session_hash = ?
`

func (q *Queries) RevokeUserSession(ctx context.Context, sessionHash []byte) error {
	_, err := q.db.ExecContext(ctx, revokeUserSession, sessionHash)
	return err
}
