// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package store

import (
	"context"
	"database/sql"
)

const createCalendar = `-- name: CreateCalendar :execresult
INSERT INTO calendars (owner_id, name, ical, members_only, description)
VALUES (?, ?, ?, ?, ?)
`

type CreateCalendarParams struct {
	OwnerID     int32
	Name        string
	Ical        []byte
	MembersOnly bool
	Description sql.Null[string]
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCalendar,
		arg.OwnerID,
		arg.Name,
		arg.Ical,
		arg.MembersOnly,
		arg.Description,
	)
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM calendars
WHERE id = ?
`

func (q *Queries) DeleteCalendar(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCalendar, id)
	return err
}

const getCalendar = `-- name: GetCalendar :one
SELECT owner_id, name, ical, members_only, description
FROM calendars
WHERE id = ?
	AND (
		NOT members_only
		OR owner_id = ?
		OR EXISTS (
			SELECT 1
			FROM users_calendars
			WHERE calendar_id = calendars.id
				AND user_id = ?
		)
	)
`

type GetCalendarParams struct {
	ID     int32
	UserID int32
}

type GetCalendarRow struct {
	OwnerID     int32
	Name        string
	Ical        []byte
	MembersOnly bool
	Description sql.Null[string]
}

func (q *Queries) GetCalendar(ctx context.Context, arg GetCalendarParams) (GetCalendarRow, error) {
	row := q.db.QueryRowContext(ctx, getCalendar, arg.ID, arg.UserID, arg.UserID)
	var i GetCalendarRow
	err := row.Scan(
		&i.OwnerID,
		&i.Name,
		&i.Ical,
		&i.MembersOnly,
		&i.Description,
	)
	return i, err
}

const getCalendarICal = `-- name: GetCalendarICal :one
SELECT ical
FROM calendars
WHERE id = ?
FOR UPDATE
`

func (q *Queries) GetCalendarICal(ctx context.Context, id int32) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getCalendarICal, id)
	var ical []byte
	err := row.Scan(&ical)
	return ical, err
}

const getCalendarOwner = `-- name: GetCalendarOwner :one
SELECT owner_id
FROM calendars
WHERE id = ?
`

func (q *Queries) GetCalendarOwner(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCalendarOwner, id)
	var owner_id int32
	err := row.Scan(&owner_id)
	return owner_id, err
}

const getOwnedCalendars = `-- name: GetOwnedCalendars :many
SELECT id
FROM calendars
WHERE owner_id = ?
`

func (q *Queries) GetOwnedCalendars(ctx context.Context, ownerID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getOwnedCalendars, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceCalendar = `-- name: ReplaceCalendar :exec
UPDATE calendars
SET ical = ?
WHERE id = ?
`

type ReplaceCalendarParams struct {
	Ical []byte
	ID   int32
}

func (q *Queries) ReplaceCalendar(ctx context.Context, arg ReplaceCalendarParams) error {
	_, err := q.db.ExecContext(ctx, replaceCalendar, arg.Ical, arg.ID)
	return err
}

const updateMetadataCalendar = `-- name: UpdateMetadataCalendar :exec
UPDATE calendars
SET name = COALESCE(?, name),
	members_only = COALESCE(?, members_only),
	description = COALESCE(?, description)
WHERE id = ?
`

type UpdateMetadataCalendarParams struct {
	Name        sql.Null[string]
	MembersOnly sql.Null[bool]
	Description sql.Null[string]
	ID          int32
}

func (q *Queries) UpdateMetadataCalendar(ctx context.Context, arg UpdateMetadataCalendarParams) error {
	_, err := q.db.ExecContext(ctx, updateMetadataCalendar,
		arg.Name,
		arg.MembersOnly,
		arg.Description,
		arg.ID,
	)
	return err
}
