// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type Calendar struct {
	ID          int32
	OwnerID     int32
	Name        string
	Ical        []byte
	MembersOnly bool
	Description sql.Null[string]
}

type CalendarsAccessCode struct {
	ID         int32
	CalendarID int32
	Code       string
	ExpiresAt  sql.NullTime
}

type User struct {
	ID           int32
	Email        string
	FirstName    string
	LastName     string
	PasswordHash []byte
	MiddleName   sql.Null[string]
}

type UsersCalendar struct {
	UserID     int32
	CalendarID int32
}

type UsersCalendarsBan struct {
	UserID     int32
	CalendarID int32
	Reason     string
	ExpiresAt  sql.NullTime
}

type UsersSession struct {
	ID        []byte
	UserID    int32
	Email     string
	ExpiresAt time.Time
}
