// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type Calendar struct {
	ID          int32
	OwnerID     int32
	Name        string
	IcalData    []byte
	Description sql.Null[string]
}

type CalendarsAccessCode struct {
	ID         int32
	CalendarID int32
	Code       string
	ExpiresAt  sql.Null[time.Time]
}

type OnlineCalendar struct {
	ID          int32
	OwnerID     int32
	Name        string
	Url         string
	Description sql.Null[string]
}

type User struct {
	ID           int32
	Email        string
	FirstName    string
	LastName     string
	PasswordHash []byte
	MiddleName   sql.Null[string]
}

type UsersExternalCalendar struct {
	UserID     int32
	CalendarID int32
}

type UsersExternalOnlineCalendar struct {
	UserID           int32
	OnlineCalendarID int32
}

type UsersSession struct {
	ID        []byte
	UserID    int32
	Email     string
	ExpiresAt time.Time
}
