// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: time.sql

package store

import (
	"context"
	"time"
)

const getCurrentTime = `-- name: GetCurrentTime :one
SELECT NOW(6) as db_time
`

func (q *Queries) GetCurrentTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getCurrentTime)
	var db_time time.Time
	err := row.Scan(&db_time)
	return db_time, err
}
