// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_sessions.sql

package store

import (
	"context"
	"time"
)

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO users_sessions (id, user_id, email, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateUserSessionParams struct {
	ID        []byte
	UserID    int32
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}

const getUserSession = `-- name: GetUserSession :one
SELECT id, user_id, email, expires_at, NOW(6) AS db_time
FROM users_sessions
WHERE id = ?
`

type GetUserSessionRow struct {
	ID        []byte
	UserID    int32
	Email     string
	ExpiresAt time.Time
	DBTime    time.Time
}

func (q *Queries) GetUserSession(ctx context.Context, id []byte) (GetUserSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSession, id)
	var i GetUserSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.DBTime,
	)
	return i, err
}

const revokeAllUserSession = `-- name: RevokeAllUserSession :exec
DELETE FROM users_sessions
WHERE user_id = ?
`

func (q *Queries) RevokeAllUserSession(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserSession, userID)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
DELETE FROM users_sessions
WHERE id = ?
`

func (q *Queries) RevokeUserSession(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, revokeUserSession, id)
	return err
}

const updateUserSession = `-- name: UpdateUserSession :exec
UPDATE users_sessions
SET email = (
	SELECT email
	FROM users
	WHERE id = users_sessions.user_id
)
WHERE user_id = ?
`

func (q *Queries) UpdateUserSession(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, updateUserSession, userID)
	return err
}
