// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_calendars.sql

package store

import (
	"context"
	"database/sql"
)

const getCalendarMembers = `-- name: GetCalendarMembers :many
SELECT user_id
FROM users_calendars
WHERE calendar_id = ?
`

func (q *Queries) GetCalendarMembers(ctx context.Context, calendarID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarMembers, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var user_id int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscribedCalendars = `-- name: GetSubscribedCalendars :many
SELECT calendar_id
FROM users_calendars
WHERE user_id = ?
`

func (q *Queries) GetSubscribedCalendars(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getSubscribedCalendars, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var calendar_id int32
		if err := rows.Scan(&calendar_id); err != nil {
			return nil, err
		}
		items = append(items, calendar_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscribedMetadata = `-- name: GetSubscribedMetadata :one
SELECT color
FROM users_calendars
WHERE user_id = ?
	AND calendar_id = ?
`

type GetSubscribedMetadataParams struct {
	UserID     int32
	CalendarID int32
}

func (q *Queries) GetSubscribedMetadata(ctx context.Context, arg GetSubscribedMetadataParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSubscribedMetadata, arg.UserID, arg.CalendarID)
	var color string
	err := row.Scan(&color)
	return color, err
}

const subscribeToCalendar = `-- name: SubscribeToCalendar :exec
INSERT INTO users_calendars (user_id, calendar_id, color)
VALUES (?, ?, ?)
`

type SubscribeToCalendarParams struct {
	UserID     int32
	CalendarID int32
	Color      string
}

func (q *Queries) SubscribeToCalendar(ctx context.Context, arg SubscribeToCalendarParams) error {
	_, err := q.db.ExecContext(ctx, subscribeToCalendar, arg.UserID, arg.CalendarID, arg.Color)
	return err
}

const unsubscribeFromCalendar = `-- name: UnsubscribeFromCalendar :exec
DELETE FROM users_calendars
WHERE user_id = ?
	AND calendar_id = ?
`

type UnsubscribeFromCalendarParams struct {
	UserID     int32
	CalendarID int32
}

func (q *Queries) UnsubscribeFromCalendar(ctx context.Context, arg UnsubscribeFromCalendarParams) error {
	_, err := q.db.ExecContext(ctx, unsubscribeFromCalendar, arg.UserID, arg.CalendarID)
	return err
}

const updateSubscribedMetadata = `-- name: UpdateSubscribedMetadata :exec
UPDATE users_calendars
SET color = COALESCE(?, color)
WHERE user_id = ?
	AND calendar_id = ?
`

type UpdateSubscribedMetadataParams struct {
	Color      sql.Null[string]
	UserID     int32
	CalendarID int32
}

func (q *Queries) UpdateSubscribedMetadata(ctx context.Context, arg UpdateSubscribedMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscribedMetadata, arg.Color, arg.UserID, arg.CalendarID)
	return err
}
