// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars_access_codes.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createCalendarCode = `-- name: CreateCalendarCode :execresult
INSERT INTO calendars_access_codes (calendar_id, code, expires_at)
VALUES (?, ?, ?)
`

type CreateCalendarCodeParams struct {
	CalendarID int32
	Code       string
	ExpiresAt  sql.NullTime
}

func (q *Queries) CreateCalendarCode(ctx context.Context, arg CreateCalendarCodeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCalendarCode, arg.CalendarID, arg.Code, arg.ExpiresAt)
}

const deleteCalendarCode = `-- name: DeleteCalendarCode :exec
DELETE FROM calendars_access_codes
WHERE id = ?
`

func (q *Queries) DeleteCalendarCode(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCalendarCode, id)
	return err
}

const getCalendarCodeCalendarID = `-- name: GetCalendarCodeCalendarID :one
SELECT calendar_id
FROM calendars_access_codes
WHERE id = ?
`

func (q *Queries) GetCalendarCodeCalendarID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCalendarCodeCalendarID, id)
	var calendar_id int32
	err := row.Scan(&calendar_id)
	return calendar_id, err
}

const getCalendarCodeFromCode = `-- name: GetCalendarCodeFromCode :one
SELECT id, calendar_id, expires_at, NOW(6) AS db_time
FROM calendars_access_codes
WHERE code = ?
`

type GetCalendarCodeFromCodeRow struct {
	ID         int32
	CalendarID int32
	ExpiresAt  sql.NullTime
	DBTime     time.Time
}

func (q *Queries) GetCalendarCodeFromCode(ctx context.Context, code string) (GetCalendarCodeFromCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getCalendarCodeFromCode, code)
	var i GetCalendarCodeFromCodeRow
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.ExpiresAt,
		&i.DBTime,
	)
	return i, err
}

const getCalendarCodeMetadata = `-- name: GetCalendarCodeMetadata :one
SELECT calendar_id, code, expires_at
FROM calendars_access_codes
WHERE id = ?
`

type GetCalendarCodeMetadataRow struct {
	CalendarID int32
	Code       string
	ExpiresAt  sql.NullTime
}

func (q *Queries) GetCalendarCodeMetadata(ctx context.Context, id int32) (GetCalendarCodeMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getCalendarCodeMetadata, id)
	var i GetCalendarCodeMetadataRow
	err := row.Scan(&i.CalendarID, &i.Code, &i.ExpiresAt)
	return i, err
}

const getCalendarCodes = `-- name: GetCalendarCodes :many
SELECT id
FROM calendars_access_codes
WHERE calendar_id = ?
`

func (q *Queries) GetCalendarCodes(ctx context.Context, calendarID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarCodes, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
