// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_calendars_bans.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const banCalendarMember = `-- name: BanCalendarMember :exec
INSERT INTO users_calendars_bans (user_id, calendar_id, reason, expires_at)
VALUES (?, ?, ?, ?)
`

type BanCalendarMemberParams struct {
	UserID     int32
	CalendarID int32
	Reason     string
	ExpiresAt  sql.NullTime
}

func (q *Queries) BanCalendarMember(ctx context.Context, arg BanCalendarMemberParams) error {
	_, err := q.db.ExecContext(ctx, banCalendarMember,
		arg.UserID,
		arg.CalendarID,
		arg.Reason,
		arg.ExpiresAt,
	)
	return err
}

const getCalendarBans = `-- name: GetCalendarBans :many
SELECT user_id
FROM users_calendars_bans
WHERE calendar_id = ?
	AND (
		expires_at IS NULL
		OR expires_at > NOW()
	)
`

func (q *Queries) GetCalendarBans(ctx context.Context, calendarID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarBans, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var user_id int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isMemberBanned = `-- name: IsMemberBanned :one
SELECT reason, expires_at, NOW(6) AS db_time
FROM users_calendars_bans
WHERE user_id = ?
	AND calendar_id = ?
`

type IsMemberBannedParams struct {
	UserID     int32
	CalendarID int32
}

type IsMemberBannedRow struct {
	Reason    string
	ExpiresAt sql.NullTime
	DBTime    time.Time
}

func (q *Queries) IsMemberBanned(ctx context.Context, arg IsMemberBannedParams) (IsMemberBannedRow, error) {
	row := q.db.QueryRowContext(ctx, isMemberBanned, arg.UserID, arg.CalendarID)
	var i IsMemberBannedRow
	err := row.Scan(&i.Reason, &i.ExpiresAt, &i.DBTime)
	return i, err
}

const unbanCalendarMember = `-- name: UnbanCalendarMember :exec
DELETE FROM users_calendars_bans
WHERE user_id = ?
	AND calendar_id = ?
`

type UnbanCalendarMemberParams struct {
	UserID     int32
	CalendarID int32
}

func (q *Queries) UnbanCalendarMember(ctx context.Context, arg UnbanCalendarMemberParams) error {
	_, err := q.db.ExecContext(ctx, unbanCalendarMember, arg.UserID, arg.CalendarID)
	return err
}
